[package]
name = "pixelpusher"
version = "0.1.0"
authors = ["Matt Stone <matthew.d.stone@gmail.com>"]
edition = "2018"

[dependencies]
hwaddr = "0.1.5"
byteorder = "1.3.1"
image = "0.21.0"
log = "0.4.6"
